In [14]:
import pandas as pd 
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [15]:
d1=pd.read_csv('Diabetes.csv')

In [16]:
d1.head(13)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0

In [17]:
d1.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [18]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [19]:
d=d1.loc[(d1['Glucose']!=0) & (d1['BloodPressure']!=0) & 
           (d1['SkinThickness']!=0) & (d1['Insulin']!=0) & (d1['BMI']!=0)]

In [20]:
d.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,3.301020,122.627551,70.663265,29.145408,156.056122,33.086224,0.523046,30.864796,0.331633
std,3.211424,30.860781,12.496092,10.516424,118.841690,7.027659,0.345488,10.200777,0.471401
min,0.000000,56.000000,24.000000,7.000000,14.000000,18.200000,0.085000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,21.000000,76.750000,28.400000,0.269750,23.000000,0.000000
50%,2.000000,119.000000,70.000000,29.000000,125.500000,33.200000,0.449500,27.000000,0.000000
75%,5.000000,143.000000,78.000000,37.000000,190.000000,37.100000,0.687000,36.000000,1.000000
max,17.000000,198.000000,110.000000,63.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [21]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 3 to 765
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               392 non-null    int64
 1   Glucose                   392 non-null    int64
 2   BloodPressure             392 non-null    int64
 3   SkinThickness             392 non-null    int64
 4   Insulin                   392 non-null    int64
 5   BMI                       392 non-null    float64
 6   DiabetesPedigreeFunction  392 non-null    float64
 7   Age                       392 non-null    int64
 8   Outcome                   392 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 30.6 KB

In [22]:
d1['Glucose'].replace(0,d['Glucose'].mean(),inplace=True)
d1['BloodPressure'].replace(0,d['BloodPressure'].mean(),inplace=True)
d1['SkinThickness'].replace(0,d['SkinThickness'].mean(),inplace=True)
d1['Insulin'].replace(0,d['Insulin'].mean(),inplace=True)
d1['BMI'].replace(0,d['BMI'].mean(),inplace=True)

In [23]:
d1.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.692888,72.325800,29.151052,155.795560,32.466469,0.471876,33.240885,0.348958
std,3.369578,30.436043,12.101807,8.790943,85.021487,6.875558,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,121.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,29.145408,156.056122,32.400000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,156.056122,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [24]:
d1.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.000000,156.056122,33.6,0.627,50,1
1,1,85.0,66.0,29.000000,156.056122,26.6,0.351,31,0
2,8,183.0,64.0,29.145408,156.056122,23.3,0.672,32,1
3,1,89.0,66.0,23.000000,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35.000000,168.000000,43.1,2.288,33,1

In [25]:
d1.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.127849,0.208850,0.082926,0.056535,0.021589,-0.033523,0.544341,0.221898
Glucose,0.127849,1.000000,0.219028,0.192985,0.419998,0.230189,0.137004,0.266453,0.492948
BloodPressure,0.208850,0.219028,1.000000,0.192796,0.072908,0.281531,-0.001108,0.325860,0.164509
SkinThickness,0.082926,0.192985,0.192796,1.000000,0.158154,0.542239,0.101030,0.127780,0.215277
Insulin,0.056535,0.419998,0.072908,0.158154,1.000000,0.166212,0.098136,0.137366,0.214532
BMI,0.021589,0.230189,0.281531,0.542239,0.166212,1.000000,0.153238,0.025207,0.311446
DiabetesPedigreeFunction,-0.033523,0.137004,-0.001108,0.101030,0.098136,0.153238,1.000000,0.033561,0.173844
Age,0.544341,0.266453,0.325860,0.127780,0.137366,0.025207,0.033561,1.000000,0.238356
Outcome,0.221898,0.492948,0.164509,0.215277,0.214532,0.311446,0.173844,0.238356,1.000000

In [26]:
x=d1.iloc[:,0:8]
# x=d1.drop("Outcome", axis=1)

In [27]:
y=d1.iloc[:,-1] #y=d1.iloc[:,8]
#y=d1.Outcome

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

In [30]:
#Fitting K-NN classifier to the training set  
from sklearn.svm import SVC
svm_classifier= SVC(kernel='rbf',degree=2,random_state=0)  # Hyper Parameter
svm_classifier.fit(x_train, y_train)

SVC(degree=2, random_state=0)

In [31]:
#Predicting the test set result  
y_pred= svm_classifier.predict(x_test)
print(y_pred)

[1 0 0 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0
 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0
 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0]

In [32]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)

In [33]:
print(cm)

[[94 13]
 [22 25]]

In [34]:
from sklearn import metrics
print("accuracy",metrics.accuracy_score(y_test,y_pred))

accuracy 0.7727272727272727

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       107
           1       0.66      0.53      0.59        47

    accuracy                           0.77       154
   macro avg       0.73      0.71      0.72       154
weighted avg       0.76      0.77      0.77       154

In [25]:
# Get Support Vector indices
support_vector_indices= svm_classifier.support_
print(support_vector_indices)

[  2  10  12  14  15  16  17  20  22  36  39  43  45  48  49  51  58  59
  64  65  70  71  76  79  82  84  93  95  96 100 102 103 105 108 109 111
 118 124 130 134 137 139 145 146 152 156 157 158 159 160 164 166 167 168
 170 171 172 179 182 183 186 187 188 192 193 203 204 207 208 211 219 224
 228 229 230 231 233 237 251 252 259 264 265 267 270 279 280 282 287 290
 293 294 295 296 298 299 300 303 305 311 312 315 316 320 322 325 326 329
 331 336 341 343 344 347 352 355 356 357 360 367 370 373 378 383 387 397
 402 412 413 416 417 418 420 422 423 427 429 436 440 441 446 448 450 453
 454 463 465 466 468 475 478 482 483 484 494 495 496 497 501 502 504 510
 514 520 523 528 530 532 545 550 553 556 558 563 565 571 577 580 589 590
 595 600 605 608 612 613   4   5   6   7  11  18  19  26  27  29  30  32
  33  34  41  42  50  54  56  62  63  66  68  69  72  73  77  80  81  87
  89  91  97  99 112 113 114 115 120 121 123 126 127 135 141 147 150 153
 154 163 165 169 175 176 177 178 184 189 190 196 197 199 201 202 210 213
 216 222 226 238 242 244 245 246 249 253 254 258 262 266 271 277 283 285
 291 301 302 306 307 308 310 313 314 318 321 323 328 332 335 337 338 340
 342 346 348 350 353 354 359 364 365 368 374 379 381 390 394 395 401 404
 406 407 409 414 415 419 424 426 430 432 433 434 435 437 445 447 451 452
 455 456 464 470 471 472 473 476 477 481 485 507 508 509 511 518 519 521
 522 525 529 531 533 535 540 549 551 557 564 568 581 582 583 584 586 587
 588 591 597 601 606 610]

In [26]:
# Get number of support_vector per class
support_vector_per_class= svm_classifier.n_support_
print(support_vector_per_class)

[186 180]

# K Fold Cross Validation

In [37]:
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import KFold
from sklearn import model_selection
kfold = KFold(n_splits=10)
cv_results = model_selection.cross_val_score(svm_classifier, x, y, cv=kfold)

In [38]:
print(cv_results)

[0.72727273 0.80519481 0.71428571 0.63636364 0.74025974 0.79220779
 0.77922078 0.83116883 0.77631579 0.77631579]

In [39]:
print(cv_results.mean())

0.7578605604921395

# GridSearchCV

In [36]:
from sklearn.model_selection import GridSearchCV
parameters = {'C':[0.01,0.05,10,20,30],
              'degree':[2,3,4],
              'gamma':[0.001,0.01],
              'kernel':['rbf']
             }        
c1 = SVC()  
grid = GridSearchCV(c1, parameters, cv=10)
grid.fit(x,y)
print(grid.best_params_)
print(grid.best_estimator_)

{'C': 10, 'degree': 2, 'gamma': 0.001, 'kernel': 'rbf'}
SVC(C=10, degree=2, gamma=0.001)

In [42]:
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

0.7187286397812713
{'C': 10, 'degree': 2, 'gamma': 0.001, 'kernel': 'rbf'}
SVC(C=10, degree=2, gamma=0.001)